---
- name: "Install sosreport"
  ansible.builtin.package:
    name: sos
    state: installed

- name: "Run sosreport"
  command: "sosreport --batch"
  register: sosreport_cmd

- name: "Extract sosreport tarball name"
  ansible.builtin.set_fact:
    sosreport_tarball: "{{ sosreport_cmd.stdout_lines|select('match', '^\\s*/var/tmp/sosreport-.*')|first|trim }}"

- name: "Get sosreport tarball size"
  ansible.builtin.stat:
    path: "{{ sosreport_tarball }}"
  register: sosreport_stat

- name: "Check sosreport tarball file exists"
  ansible.builtin.assert:
    that:
      - sosreport_stat.stat.exists
    quiet: yes

- name: "Show info about remote sosreport tarballs"
  ansible.builtin.debug:
    msg: "Generated {{ sosreport_tarball }} in {{ sosreport_cmd.delta }} seconds with file size {{ sosreport_stat.stat.size|filesizeformat }}"

- name: "Show direcotry we will be fetching to"
  ansible.builtin.debug:
    var: sosreport_gatherer_local_dir
  run_once: yes

- name: "Cleanup local sosreport tarballs dir"
  ansible.builtin.file:
    path: "{{ sosreport_gatherer_local_dir }}"
    state: absent
  delegate_to: localhost

- name: "Fetch sosreport tarballs"
  ansible.builtin.fetch:
    src: "{{ sosreport_tarball }}"
    dest: "{{ sosreport_gatherer_local_dir }}"
    flat: yes

- name: "Cleanup remote sosreport tarballs"
  ansible.builtin.file:
    path: "{{ sosreport_tarball }}"
    state: absent
...
